# Exercitii

# Exercitiul 1

In [ ]:
import torch

A = torch.rand(2, dtype=torch.float32)
B = torch.rand(2, 2, dtype=torch.float32)
C = torch.rand(2, 2, 2, dtype=torch.float32)
print(f"Tensor A shape {A.shape}")
print(f"Tensor B shape {B.shape}")
print(f"Tensor C shape {C.shape}")

Tensor A shape torch.Size([2])
Tensor B shape torch.Size([2, 2])
Tensor C shape torch.Size([2, 2, 2])


# Exercitiul 2

In [ ]:
x = torch.tensor([-10, 10, 8], dtype=torch.float32)
x.requires_grad_(True)
x.grad
sigmoid = 1/(1+torch.exp(-x))
sigmoid.sum().backward()
x.grad


tensor([4.5396e-05, 4.5396e-05, 3.3524e-04])

# Exercitiul 3

In [ ]:
A = torch.tensor([[1, 2, -3], [4, 5, 10]])
B = torch.tensor([[10, 11, -2], [13, -3, 8]])

In [ ]:
print(f"Hadamrad product of A and B is:\n {A * B}")
print(f"10 added to each element of B:\n {B+10}")
print(f"Transpose of A is:\n {A.T}")
print(f"Transpose of B is:\n {B.T}")

Hadamrad product of A and B is:
 tensor([[ 10,  22,   6],
        [ 52, -15,  80]])
10 added to each element of B:
 tensor([[20, 21,  8],
        [23,  7, 18]])
Transpose of A is:
 tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])
Transpose of B is:
 tensor([[10, 13],
        [11, -3],
        [-2,  8]])


# Exercitiul 4

In [ ]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
B = torch.tensor([[10, 11], [-2, 0], [1, -3]], dtype=torch.float32)

In [ ]:
C = A @ B
C

tensor([[ 9.,  2.],
        [36., 26.]])

In [ ]:
torch.norm(A)

tensor(9.5394)

In [ ]:
torch.norm(B)

tensor(15.3297)